project:
  type: website
  output-dir: docs

website:
  title: "{ Tim Gilbert }"
  favicon: assets/desertLeafShrimp.png
  navbar:
  
    left:
      - text: Home
        href: index.qmd
        
      - text: About
        href: about.qmd
        
      - text: Projects
        href: projects.qmd
        
      - text: Shiny App Examples
        href: dashboards.qmd

    right:

      - icon: github
        href: https://github.com/tgilbert14
        
      - icon: envelope
        href: mailto:tsgilbert@arizona.edu
        
      - text: CV
        href: resume.qmd
        
      - icon: linkedin
        href: www.linkedin.com/in/tgilbert14
        
      - icon: instagram
        href: https://www.instagram.com/timbogilbert/
        
      - icon: heart
        href: https://www.buymeacoffee.com/tgilbert14
        
      - icon: gift
        href: https://account.venmo.com/u/tsgilbert

        
        

format:
  html:
    theme: flatly
    css: styles.css
    toc: true